title: Walker Hughes Portfolio
description: Walker Hughes Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

# Colour gradient for the header
header-colors: 
  # right: "#8a108c"
  # left: "#cc580c"

  right: "#000000"
  left: "#000000"